'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class a_manage

    '''<summary>
    '''Head1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Head1 As Global.System.Web.UI.HtmlControls.HtmlHead

    '''<summary>
    '''formBody control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents formBody As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''panelMenu control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents panelMenu As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''labelKomunikat control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents labelKomunikat As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Panel2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel2 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''Label2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LIleDokumentow control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LIleDokumentow As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TBFiltrowanie control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TBFiltrowanie As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TBSzukajNrZamow control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TBSzukajNrZamow As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TBRocznik control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TBRocznik As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''GridViewDyspozycje control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GridViewDyspozycje As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''LMagazyn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LMagazyn As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LPakowanie control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LPakowanie As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LWstrzymane control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LWstrzymane As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LBlokadaNaHippo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBlokadaNaHippo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LBlokadaNaBurek control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBlokadaNaBurek As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LWznowione control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LWznowione As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LPrzeslanoNaDocelowy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LPrzeslanoNaDocelowy As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LPodjete control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LPodjete As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LSpakowane control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LSpakowane As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LPilne control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LPilne As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LRezygnacjaWlasna control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LRezygnacjaWlasna As Global.System.Web.UI.WebControls.Label
End Class
