'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class package

    '''<summary>
    '''Head1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Head1 As Global.System.Web.UI.HtmlControls.HtmlHead

    '''<summary>
    '''formBody control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents formBody As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''panelMenu control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents panelMenu As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''DDLOperator control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DDLOperator As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''labelKomunikat control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents labelKomunikat As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''BRefreshPage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BRefreshPage As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''TBEtykieta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TBEtykieta As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''PanelPakowanie control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PanelPakowanie As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''Label2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LIleDokumentow control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LIleDokumentow As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''PanelDodawaniePaczki control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PanelDodawaniePaczki As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''LNrZamowienia control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LNrZamowienia As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LNr_list_przewozowy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LNr_list_przewozowy As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LSchemat control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LSchemat As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''HLEtykietaPDF_INPOST control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HLEtykietaPDF_INPOST As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''LPaczkaID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LPaczkaID As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TBROW_DDLFirma control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TBROW_DDLFirma As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''DDLFirma control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DDLFirma As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''BGenerujEtykiete_INPOST control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BGenerujEtykiete_INPOST As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''BGenerujOferte_INPOST control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BGenerujOferte_INPOST As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''BPobierzPDF_INPOST control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BPobierzPDF_INPOST As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''BDrukowaniePDF_INPOST control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BDrukowaniePDF_INPOST As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''BZerowanie_INPOST control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BZerowanie_INPOST As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''TBROW_SR_COUNTRY control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TBROW_SR_COUNTRY As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''TB_SR_COUNTRY control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TB_SR_COUNTRY As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TBROW_TB_ST_SHIPMENT_DATE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TBROW_TB_ST_SHIPMENT_DATE As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''TB_ST_SHIPMENT_DATE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TB_ST_SHIPMENT_DATE As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TBROW_TB_B_COSTS_CENTER control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TBROW_TB_B_COSTS_CENTER As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''TB_B_COSTS_CENTER control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TB_B_COSTS_CENTER As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TBROW_SR_POST_NUM control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TBROW_SR_POST_NUM As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''TB_SR_POST_NUM control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TB_SR_POST_NUM As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TBROW_SERVICE_TYPE_INPOST control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TBROW_SERVICE_TYPE_INPOST As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''TB_SERVICE_TYPE_INPOST control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TB_SERVICE_TYPE_INPOST As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TBROW_LABEL_TYPE_INPOST control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TBROW_LABEL_TYPE_INPOST As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''TB_LABEL_TYPE_INPOST control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TB_LABEL_TYPE_INPOST As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TBROW_SR_NAME control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TBROW_SR_NAME As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''TB_SR_NAME control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TB_SR_NAME As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TBROW_SR_COMPANY_INPOST control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TBROW_SR_COMPANY_INPOST As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''TB_SR_COMPANY_INPOST control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TB_SR_COMPANY_INPOST As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TBROW_SR_FIRSTNAME_INPOST control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TBROW_SR_FIRSTNAME_INPOST As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''TB_SR_FIRSTNAME_INPOST control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TB_SR_FIRSTNAME_INPOST As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TBROW_SR_LASTNAME_INPOST control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TBROW_SR_LASTNAME_INPOST As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''TB_SR_LASTNAME_INPOST control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TB_SR_LASTNAME_INPOST As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TBROW_SR_POSTAL_CODE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TBROW_SR_POSTAL_CODE As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''TB_SR_POSTAL_CODE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TB_SR_POSTAL_CODE As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TBROW_SR_CITY control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TBROW_SR_CITY As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''TB_SR_CITY control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TB_SR_CITY As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TBROW_SR_STREET control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TBROW_SR_STREET As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''TB_SR_STREET control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TB_SR_STREET As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TBROW_SR_HOUSE_NUM control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TBROW_SR_HOUSE_NUM As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''TB_SR_HOUSE_NUM control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TB_SR_HOUSE_NUM As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TBROW_SR_APART_NUM control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TBROW_SR_APART_NUM As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''TB_SR_APART_NUM control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TB_SR_APART_NUM As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TBROW_PC_PERSON_NAME control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TBROW_PC_PERSON_NAME As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''TB_PC_PERSON_NAME control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TB_PC_PERSON_NAME As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TBROW_PC_PHONE_NUM control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TBROW_PC_PHONE_NUM As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''TB_PC_PHONE_NUM control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TB_PC_PHONE_NUM As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TBROW_PC_EMAIL_ADD control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TBROW_PC_EMAIL_ADD As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''TB_PC_EMAIL_ADD control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TB_PC_EMAIL_ADD As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''DDLTyp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DDLTyp As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''TBCELL_RodzajINPOST_ALLEGRO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TBCELL_RodzajINPOST_ALLEGRO As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''DDLRodzajINPOST_ALLEGRO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DDLRodzajINPOST_ALLEGRO As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''DDL_CONTENT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DDL_CONTENT As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''DDLRodzajStandard control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DDLRodzajStandard As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''TBWagaCOM control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TBWagaCOM As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TBWaga control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TBWaga As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TBIlePaczek control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TBIlePaczek As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''WymiarySzczegoloweINPOST control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents WymiarySzczegoloweINPOST As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''TBSzerINPOST_ALLEGRO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TBSzerINPOST_ALLEGRO As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TBWysINPOST_ALLEGRO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TBWysINPOST_ALLEGRO As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TBDlugINPOST_ALLEGRO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TBDlugINPOST_ALLEGRO As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TB_COMMENT_F_INPOST control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TB_COMMENT_F_INPOST As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''UslugaCodINPOST control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UslugaCodINPOST As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''TB_COD_INPOST control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TB_COD_INPOST As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TBOpisZam control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TBOpisZam As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TBProcessDirectory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TBProcessDirectory As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TBProcessOutput control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TBProcessOutput As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TablePackageButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TablePackageButton As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''BDodajPaczke control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BDodajPaczke As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''BAnulujPaczek control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BAnulujPaczek As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''HyperLink1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HyperLink1 As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''BPobierzWage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BPobierzWage As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''GridViewPaczki control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GridViewPaczki As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''GridViewIndeksy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GridViewIndeksy As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''Table2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Table2 As Global.System.Web.UI.WebControls.Table

    '''<summary>
    '''BZakonczPakowanie control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BZakonczPakowanie As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''PanelPakowanieData control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PanelPakowanieData As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''GridViewPakowanie control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GridViewPakowanie As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''Ldajar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Ldajar As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Ldominus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Ldominus As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LPodjete control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LPodjete As Global.System.Web.UI.WebControls.Label
End Class
